services:
  # Flask Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial_valuation_backend
    ports:
      - "8001:5000"  # Changed from 8000 to 8001
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: financial_valuation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Celery Worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial_valuation_celery
    command: celery -A app.services.celery_service.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial_valuation_frontend
    ports:
      - "3001:3000"  # Changed from 3000 to 3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api

volumes:
  redis_data: 