services:
  # Flask Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial_valuation_backend
    ports:
      - "8001:5000"  # Changed from 8000 to 8001
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial_valuation_frontend
    ports:
      - "3001:3000"  # Changed from 3000 to 3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api 